### ISSUE TITLE
move msg

### ISSUE THREAD

**Issue by trikiman** [laralove143/interchannel-message-mover#10]
u cant move msg twice. its just removed. and it is sad.

**Comment by laralove143** [comment]
is this a duplicate of #12

**Comment by trikiman** [comment]
no this is other one. its mean u can move twice. its just dissapear.

**Comment by laralove143** [comment]
What do you mean? I don't understand

**Comment by trikiman** [comment]
if u move msg 1 time to other channel all good, but if u move it again its just disappears.

**Comment by laralove143** [comment]
You mean moving the same message twice?

**Comment by laralove143** [comment]
That's included in #9
