### ISSUE TITLE
proposal: change `/move_last_messages` to be a message command "move this message and below"

### ISSUE THREAD

**Issue by laralove143** [laralove143/interchannel-message-mover#14]
**pros:**

its not good ux to make users count up messages, especially for more than 20 messages, with this change the 20 messages limit could be raised

**cons:**

its not as discoverable as simply typing `/`, users would have to _right click/hold on a message, hover over/tap apps, click/tap move messages after this message_ but the bot's bio could mention these message commands

**execution:**

when the command is executed,
the bot replies with a message (to be changed to a modal/pop-up once discord supports it) which has a menu button for selecting the channel to move the messages to, when selected, the messages are moved

**Comment by tartaros-afk** [comment]
people will instinctively go to the first message they want to move, not to the last message they want to keep  

to the point that I had to reread "move messages after this message" a couple times before I groked it and I'm fairly certain this is the kind of thing I'd forget and screw up   

suggest changing it to "move this message and below" or "move this message and all after" or something like that  

REALLY love the idea of this functionality, even if it's less obvious to people not used to using the message > app functionality. it's a bit more hidden and less obvious but so much easier to do without screwing up stuff like counting, and it could exist in addition to a slash command that takes number parameters

**Comment by laralove143** [comment]
the name length limit set by discord is 32, which _move this message and below_ is under, while the other sadly isnt
